// ============================================================================
// FORZA HORIZON UZ - 40 TA MASHINA BAZASI (CARS DATA)
// O'zbekiston milliy avtomobillari va jahonning eng mashhur superkarlari
// ============================================================================

export const CARS_DATA = [
  // --- 1. O'ZBEKISTON MILLIY AVTOMOBILLARI ---
  {
    id: "matiz",
    name: "Daewoo Matiz Best",
    category: "uzbek",
    brand: "Daewoo",
    price: 0, // Boshlang'ich tekin mashina
    unlocked: true,
    tier: "Hamyonbop",
    topSpeed: 145, // km/h
    accel: 12.5,   // 0-100 s
    handling: 78,  // 100 dan
    braking: 70,
    weight: 820,   // kg
    hp: 64,
    drive: "FWD",
    bodyType: "hatchback",
    dimensions: { length: 3.5, width: 1.5, height: 1.48 },
    color: "#e63946",
    desc: "Shahar tirbandliklarining yengilmas qahramoni! Yengil, epchil va kamxarj."
  },
  {
    id: "spark",
    name: "Chevrolet Spark R2",
    category: "uzbek",
    brand: "Chevrolet",
    price: 8500,
    unlocked: false,
    tier: "Hamyonbop",
    topSpeed: 165,
    accel: 11.0,
    handling: 82,
    braking: 75,
    weight: 940,
    hp: 85,
    drive: "FWD",
    bodyType: "hatchback",
    dimensions: { length: 3.65, width: 1.6, height: 1.5 },
    color: "#ffffff",
    desc: "Yoshlarbop, zamonaviy dizayn va o'ta chaqqon shahar hetchbegi."
  },
  {
    id: "damas",
    name: "Chevrolet Damas Deluxe",
    category: "uzbek",
    brand: "Chevrolet",
    price: 9200,
    unlocked: false,
    tier: "Hamyonbop",
    topSpeed: 125,
    accel: 15.0,
    handling: 65,
    braking: 68,
    weight: 850,
    hp: 43,
    drive: "RWD",
    bodyType: "van",
    dimensions: { length: 3.48, width: 1.4, height: 1.9 },
    color: "#ffffff",
    desc: "O'zbekiston yo'llarining tirik afsonasi! Orqa uzatmali va kutilmagan drift qobiliyatiga ega."
  },
  {
    id: "nexia1",
    name: "Daewoo Nexia 1 (DONC)",
    category: "uzbek",
    brand: "Daewoo",
    price: 6000,
    unlocked: false,
    tier: "Klassika",
    topSpeed: 175,
    accel: 10.8,
    handling: 74,
    braking: 72,
    weight: 1020,
    hp: 85,
    drive: "FWD",
    bodyType: "sedan",
    dimensions: { length: 4.48, width: 1.66, height: 1.39 },
    color: "#4a5568",
    desc: "O'z davrining qiroli! Chidamlilik va tezlik timsoli bo'lgan birinchi Nexia."
  },
  {
    id: "nexia2",
    name: "Daewoo Nexia 2 (SOHC)",
    category: "uzbek",
    brand: "Daewoo",
    price: 7500,
    unlocked: false,
    tier: "Klassika",
    topSpeed: 180,
    accel: 10.5,
    handling: 75,
    braking: 74,
    weight: 1040,
    hp: 92,
    drive: "FWD",
    bodyType: "sedan",
    dimensions: { length: 4.5, width: 1.68, height: 1.4 },
    color: "#silver",
    desc: "Yangilangan optika va o'tkir bamperga ega xalqona sedan."
  },
  {
    id: "nexia3",
    name: "Chevrolet Nexia 3 (Ravon R3)",
    category: "uzbek",
    brand: "Chevrolet",
    price: 11000,
    unlocked: false,
    tier: "Standart",
    topSpeed: 185,
    accel: 9.8,
    handling: 80,
    braking: 78,
    weight: 1080,
    hp: 106,
    drive: "FWD",
    bodyType: "sedan",
    dimensions: { length: 4.33, width: 1.69, height: 1.5 },
    color: "#2b6cb0",
    desc: "1.5L tejamkor dvigatel, qulay salon va ishonchli shahar avtomobili."
  },
  {
    id: "cobalt",
    name: "Chevrolet Cobalt 1.5",
    category: "uzbek",
    brand: "Chevrolet",
    price: 12500,
    unlocked: false,
    tier: "Standart",
    topSpeed: 188,
    accel: 9.5,
    handling: 81,
    braking: 79,
    weight: 1190,
    hp: 106,
    drive: "FWD",
    bodyType: "sedan",
    dimensions: { length: 4.48, width: 1.73, height: 1.51 },
    color: "#ffffff",
    desc: "O'zbekistonning eng ommabop oilaviy sedani. Yumshoq podveska va keng bagaj."
  },
  {
    id: "gentra",
    name: "Chevrolet Lacetti / Gentra (Black)",
    category: "uzbek",
    brand: "Chevrolet",
    price: 14500,
    unlocked: false,
    tier: "Lyuks / Tyuning",
    topSpeed: 195,
    accel: 9.1,
    handling: 85,
    braking: 82,
    weight: 1240,
    hp: 107,
    drive: "FWD",
    bodyType: "sedan",
    dimensions: { length: 4.51, width: 1.72, height: 1.44 },
    color: "#111111",
    desc: "Tyuning ishqibozlarining sevimli mashinasi! Taniqli 'Qora Gentra' uslubi."
  },
  {
    id: "onix",
    name: "Chevrolet Onix Premier Turbo",
    category: "uzbek",
    brand: "Chevrolet",
    price: 18000,
    unlocked: false,
    tier: "Zamonaviy",
    topSpeed: 205,
    accel: 8.7,
    handling: 86,
    braking: 84,
    weight: 1120,
    hp: 132,
    drive: "FWD",
    bodyType: "sedan",
    dimensions: { length: 4.47, width: 1.73, height: 1.47 },
    color: "#3182ce",
    desc: "1.2 Turbo motor, zamonaviy optika va raqamli panelga ega dinamik sedan."
  },
  {
    id: "tracker",
    name: "Chevrolet Tracker 2 Premier",
    category: "uzbek",
    brand: "Chevrolet",
    price: 22000,
    unlocked: false,
    tier: "Krossover",
    topSpeed: 200,
    accel: 8.9,
    handling: 83,
    braking: 85,
    weight: 1280,
    hp: 132,
    drive: "FWD",
    bodyType: "suv",
    dimensions: { length: 4.27, width: 1.79, height: 1.62 },
    color: "#c53030",
    desc: "Baland klirens, panoramali tom va sport uslubidagi kompakt krossover."
  },
  {
    id: "malibu1",
    name: "Chevrolet Malibu 1 (2.4L)",
    category: "uzbek",
    brand: "Chevrolet",
    price: 19000,
    unlocked: false,
    tier: "Biznes",
    topSpeed: 215,
    accel: 8.2,
    handling: 84,
    braking: 84,
    weight: 1530,
    hp: 167,
    drive: "FWD",
    bodyType: "sedan",
    dimensions: { length: 4.86, width: 1.85, height: 1.46 },
    color: "#2d3748",
    desc: "Vakillik sinfidagi og'ir, barqaror va salobatli biznes sedan."
  },
  {
    id: "malibu2",
    name: "Chevrolet Malibu 2 (2.0 Turbo Redline)",
    category: "uzbek",
    brand: "Chevrolet",
    price: 32000,
    unlocked: false,
    tier: "Biznes Sport",
    topSpeed: 250,
    accel: 6.3,
    handling: 88,
    braking: 89,
    weight: 1470,
    hp: 253,
    drive: "FWD",
    bodyType: "sedan",
    dimensions: { length: 4.92, width: 1.85, height: 1.46 },
    color: "#1a202c",
    desc: "253 ot kuchi, 2.0 Turbo! Shahar ko'chalarida tengsiz tezlanishga ega qora afsona."
  },
  {
    id: "captiva",
    name: "Chevrolet Captiva 4 (V6)",
    category: "uzbek",
    brand: "Chevrolet",
    price: 25000,
    unlocked: false,
    tier: "Yo'ltanlamas",
    topSpeed: 205,
    accel: 8.5,
    handling: 80,
    braking: 83,
    weight: 1850,
    hp: 258,
    drive: "AWD",
    bodyType: "suv",
    dimensions: { length: 4.67, width: 1.85, height: 1.72 },
    color: "#4a5568",
    desc: "Kuchli V6 dvigatel, to'liq uzatma (AWD) va 7 o'rindiqli qulay yo'ltanlamas."
  },
  {
    id: "epica",
    name: "Chevrolet Epica (6-Cylinder)",
    category: "uzbek",
    brand: "Chevrolet",
    price: 13000,
    unlocked: false,
    tier: "Klassika Biznes",
    topSpeed: 210,
    accel: 8.8,
    handling: 82,
    braking: 81,
    weight: 1490,
    hp: 156,
    drive: "FWD",
    bodyType: "sedan",
    dimensions: { length: 4.8, width: 1.81, height: 1.45 },
    color: "#718096",
    desc: "6 silindrli qator dvigatelning mayin g'uvillashi va yuqori darajadagi qulaylik."
  },

  // --- 2. JAPONIYA VA AQSH SPORT AFSONALARI ---
  {
    id: "supra_mk4",
    name: "Toyota Supra MK4 (2JZ-GTE)",
    category: "sport",
    brand: "Toyota",
    price: 75000,
    unlocked: false,
    tier: "JDM Afsona",
    topSpeed: 285,
    accel: 4.4,
    handling: 91,
    braking: 89,
    weight: 1510,
    hp: 330,
    drive: "RWD",
    bodyType: "sport",
    dimensions: { length: 4.52, width: 1.81, height: 1.27 },
    color: "#e53e3e",
    desc: "Afsonaviy 2JZ motor! Tyuning orqali 1000 ot kuchigacha chiqara oladigan poyga qiroli."
  },
  {
    id: "supra_mk5",
    name: "Toyota GR Supra 3.0",
    category: "sport",
    brand: "Toyota",
    price: 65000,
    unlocked: false,
    tier: "Zamonaviy Sport",
    topSpeed: 290,
    accel: 3.9,
    handling: 93,
    braking: 92,
    weight: 1520,
    hp: 382,
    drive: "RWD",
    bodyType: "sport",
    dimensions: { length: 4.38, width: 1.85, height: 1.29 },
    color: "#dd6b20",
    desc: "Gazoo Racing tomonidan sayqallangan ideal muvozanat va turbo quvvat."
  },
  {
    id: "gtr_r35",
    name: "Nissan GT-R Nismo (R35)",
    category: "sport",
    brand: "Nissan",
    price: 140000,
    unlocked: false,
    tier: "Superkar",
    topSpeed: 330,
    accel: 2.7,
    handling: 96,
    braking: 95,
    weight: 1720,
    hp: 600,
    drive: "AWD",
    bodyType: "sport",
    dimensions: { length: 4.69, width: 1.89, height: 1.37 },
    color: "#edf2f7",
    desc: "'Godzilla' laqabli yapon dahosi! ATTESA E-TS to'liq uzatmasi bilan chaqmoqdek start oladi."
  },
  {
    id: "rx7_fd",
    name: "Mazda RX-7 Spirit R (FD3S)",
    category: "sport",
    brand: "Mazda",
    price: 68000,
    unlocked: false,
    tier: "JDM Afsona",
    topSpeed: 265,
    accel: 5.0,
    handling: 94,
    braking: 90,
    weight: 1270,
    hp: 280,
    drive: "RWD",
    bodyType: "sport",
    dimensions: { length: 4.28, width: 1.76, height: 1.23 },
    color: "#2b6cb0",
    desc: "Rotorli 13B dvigatel, 50:50 vazn taqsimoti va betakror drift boshqaruvi."
  },
  {
    id: "silvia_s15",
    name: "Nissan Silvia Spec-R (S15)",
    category: "sport",
    brand: "Nissan",
    price: 52000,
    unlocked: false,
    tier: "Drift Qiroli",
    topSpeed: 250,
    accel: 5.4,
    handling: 95,
    braking: 88,
    weight: 1240,
    hp: 250,
    drive: "RWD",
    bodyType: "sport",
    dimensions: { length: 4.44, width: 1.69, height: 1.28 },
    color: "#48bb78",
    desc: "SR20DET turbo motori bilan jihozlangan drift musobaqalarining yulduzi."
  },
  {
    id: "challenger_hellcat",
    name: "Dodge Challenger SRT Hellcat",
    category: "muscle",
    brand: "Dodge",
    price: 85000,
    unlocked: false,
    tier: "Muskul Kar",
    topSpeed: 320,
    accel: 3.5,
    handling: 84,
    braking: 91,
    weight: 2010,
    hp: 717,
    drive: "RWD",
    bodyType: "muscle",
    dimensions: { length: 5.02, width: 1.92, height: 1.46 },
    color: "#e53e3e",
    desc: "6.2L Supercharged HEMI V8! Quloqni qomatga keltiruvchi vovullash va asfaltni yondiruvchi quvvat."
  },
  {
    id: "charger_hellcat",
    name: "Dodge Charger Widebody Hellcat",
    category: "muscle",
    brand: "Dodge",
    price: 89000,
    unlocked: false,
    tier: "Muskul Kar",
    topSpeed: 315,
    accel: 3.6,
    handling: 85,
    braking: 92,
    weight: 2080,
    hp: 707,
    drive: "RWD",
    bodyType: "muscle",
    dimensions: { length: 5.1, width: 1.98, height: 1.46 },
    color: "#2d3748",
    desc: "To'rt eshikli jahondagi eng baquvvat muskul-sedan."
  },
  {
    id: "viper_acr",
    name: "Dodge Viper ACR Extreme",
    category: "supercar",
    brand: "Dodge",
    price: 160000,
    unlocked: false,
    tier: "Trek Yirtqichi",
    topSpeed: 335,
    accel: 3.3,
    handling: 97,
    braking: 98,
    weight: 1530,
    hp: 645,
    drive: "RWD",
    bodyType: "supercar",
    dimensions: { length: 4.46, width: 1.94, height: 1.24 },
    color: "#1a202c",
    desc: "8.4L gigant V10 dvigatel va ulkan aerodinamik spoylerga ega trek rekordsmeni."
  },
  {
    id: "mustang_shelby",
    name: "Ford Mustang Shelby GT500",
    category: "muscle",
    brand: "Ford",
    price: 95000,
    unlocked: false,
    tier: "Muskul Kar",
    topSpeed: 305,
    accel: 3.4,
    handling: 88,
    braking: 94,
    weight: 1890,
    hp: 760,
    drive: "RWD",
    bodyType: "muscle",
    dimensions: { length: 4.83, width: 1.94, height: 1.38 },
    color: "#3182ce",
    desc: "760 ot kuchi va Tremec 7-pog'onali tezkor robot karobka bilan yovvoyi kobralar yetakchisi."
  },
  {
    id: "corvette_c8",
    name: "Chevrolet Corvette C8 Z06",
    category: "supercar",
    brand: "Chevrolet",
    price: 125000,
    unlocked: false,
    tier: "Superkar",
    topSpeed: 315,
    accel: 2.8,
    handling: 95,
    braking: 95,
    weight: 1560,
    hp: 670,
    drive: "RWD",
    bodyType: "supercar",
    dimensions: { length: 4.69, width: 2.02, height: 1.23 },
    color: "#d69e2e",
    desc: "O'rta motorli arxitektura va tabiiy nafas oluvchi eng kuchli V8 dvigateli."
  },

  // --- 3. NEMIS SUPER AVTOMOBILLARI ---
  {
    id: "bmw_m5_cs",
    name: "BMW M5 CS (F90)",
    category: "supercar",
    brand: "BMW",
    price: 145000,
    unlocked: false,
    tier: "Super Sedan",
    topSpeed: 310,
    accel: 2.9,
    handling: 94,
    braking: 96,
    weight: 1825,
    hp: 635,
    drive: "AWD",
    bodyType: "sedan",
    dimensions: { length: 5.0, width: 1.9, height: 1.47 },
    color: "#234e52",
    desc: "BMW tarixidagi eng kuchli va yengillashtirilgan M5. Sariq lazer faralar va karbon detallar."
  },
  {
    id: "bmw_m3_g80",
    name: "BMW M3 Competition (G80)",
    category: "sport",
    brand: "BMW",
    price: 92000,
    unlocked: false,
    tier: "Sport Kar",
    topSpeed: 295,
    accel: 3.4,
    handling: 93,
    braking: 94,
    weight: 1730,
    hp: 510,
    drive: "AWD",
    bodyType: "sedan",
    dimensions: { length: 4.79, width: 1.9, height: 1.43 },
    color: "#319795",
    desc: "O'tkir radiator panjarasi, M xDrive va xarakterli drift rejimi."
  },
  {
    id: "bmw_m8",
    name: "BMW M8 Competition Gran Coupe",
    category: "supercar",
    brand: "BMW",
    price: 155000,
    unlocked: false,
    tier: "Lyuks Gran Turismo",
    topSpeed: 315,
    accel: 3.1,
    handling: 92,
    braking: 95,
    weight: 1980,
    hp: 625,
    drive: "AWD",
    bodyType: "sedan",
    dimensions: { length: 5.1, width: 1.94, height: 1.42 },
    color: "#1a202c",
    desc: "Cheksiz quvvat va 5 yulduzli qulaylikni birlashtirgan flagman."
  },
  {
    id: "amg_gt_black",
    name: "Mercedes-AMG GT Black Series",
    category: "supercar",
    brand: "Mercedes",
    price: 325000,
    unlocked: false,
    tier: "Superkar",
    topSpeed: 330,
    accel: 3.1,
    handling: 98,
    braking: 99,
    weight: 1540,
    hp: 730,
    drive: "RWD",
    bodyType: "supercar",
    dimensions: { length: 4.6, width: 2.0, height: 1.28 },
    color: "#dd6b20",
    desc: "Nürburgring rekordsmeni! 730 ot kuchiga ega Flat-Plane V8 BiTurbo va ikki qavatli karbon qanot."
  },
  {
    id: "g63_amg",
    name: "Mercedes-AMG G63 'Gelik'",
    category: "suv",
    brand: "Mercedes",
    price: 210000,
    unlocked: false,
    tier: "Lyuks Yo'ltanlamas",
    topSpeed: 240,
    accel: 4.4,
    handling: 81,
    braking: 89,
    weight: 2560,
    hp: 585,
    drive: "AWD",
    bodyType: "suv",
    dimensions: { length: 4.87, width: 1.98, height: 1.97 },
    color: "#000000",
    desc: "To'xtatib bo'lmas shon-shuhrat va maqom ramzi! Yon tomonga chiqarilgan guldurlovchi sport glushitellar."
  },
  {
    id: "amg_e63s",
    name: "Mercedes-AMG E63 S 4MATIC+",
    category: "supercar",
    brand: "Mercedes",
    price: 135000,
    unlocked: false,
    tier: "Super Sedan",
    topSpeed: 305,
    accel: 3.3,
    handling: 92,
    braking: 94,
    weight: 1950,
    hp: 612,
    drive: "AWD",
    bodyType: "sedan",
    dimensions: { length: 4.98, width: 1.87, height: 1.46 },
    color: "#718096",
    desc: "Yashirin qotil! Tashqaridan xotirjam biznes sedan, trekda esa superkarlarni dog'da qoldiradi."
  },
  {
    id: "audi_r8",
    name: "Audi R8 V10 Performance",
    category: "supercar",
    brand: "Audi",
    price: 185000,
    unlocked: false,
    tier: "Superkar",
    topSpeed: 335,
    accel: 3.1,
    handling: 96,
    braking: 97,
    weight: 1595,
    hp: 620,
    drive: "AWD",
    bodyType: "supercar",
    dimensions: { length: 4.43, width: 1.94, height: 1.24 },
    color: "#3182ce",
    desc: "5.2L atmosferali V10 simfoniyasi va quattro to'liq uzatmasining mislsiz ilashimi."
  },
  {
    id: "porsche_gt3rs",
    name: "Porsche 911 GT3 RS (992)",
    category: "supercar",
    brand: "Porsche",
    price: 280000,
    unlocked: false,
    tier: "Trek Standarti",
    topSpeed: 300,
    accel: 3.0,
    handling: 100,
    braking: 100,
    weight: 1450,
    hp: 525,
    drive: "RWD",
    bodyType: "supercar",
    dimensions: { length: 4.57, width: 1.9, height: 1.32 },
    color: "#ffffff",
    desc: "Dunyoning eng mukammal trek avtomobili! DRS faol aerodinamikasi va 9000 aylanishli motor."
  },

  // --- 4. GIPERKARLAR VA EKSKLUZIVLAR ---
  {
    id: "lambo_aventador",
    name: "Lamborghini Aventador SVJ",
    category: "hypercar",
    brand: "Lamborghini",
    price: 520000,
    unlocked: false,
    tier: "Giperkar",
    topSpeed: 355,
    accel: 2.8,
    handling: 97,
    braking: 98,
    weight: 1525,
    hp: 770,
    drive: "AWD",
    bodyType: "hypercar",
    dimensions: { length: 4.94, width: 2.1, height: 1.14 },
    color: "#38a169",
    desc: "6.5L V12 atmosferali yirtqich! ALA 2.0 faol aerodinamikasi va yuqoriga ochiluvchi lambo eshiklar."
  },
  {
    id: "lambo_huracan",
    name: "Lamborghini Huracán STO",
    category: "hypercar",
    brand: "Lamborghini",
    price: 340000,
    unlocked: false,
    tier: "Giperkar",
    topSpeed: 310,
    accel: 3.0,
    handling: 98,
    braking: 98,
    weight: 1340,
    hp: 640,
    drive: "RWD",
    bodyType: "hypercar",
    dimensions: { length: 4.55, width: 1.95, height: 1.22 },
    color: "#3182ce",
    desc: "Poyga treki uchun maxsus yaratilgan engil karbon korpusli ko'cha bolidi."
  },
  {
    id: "ferrari_laferrari",
    name: "Ferrari LaFerrari Aperta",
    category: "hypercar",
    brand: "Ferrari",
    price: 1800000,
    unlocked: false,
    tier: "Eksklyuziv Giperkar",
    topSpeed: 360,
    accel: 2.6,
    handling: 99,
    braking: 99,
    weight: 1365,
    hp: 963,
    drive: "RWD",
    bodyType: "hypercar",
    dimensions: { length: 4.7, width: 1.99, height: 1.12 },
    color: "#e53e3e",
    desc: "Maranello durdonasi! V12 gibrid HY-KERS tizimi bilan jami 963 ot kuchi."
  },
  {
    id: "ferrari_488_pista",
    name: "Ferrari 488 Pista",
    category: "supercar",
    brand: "Ferrari",
    price: 360000,
    unlocked: false,
    tier: "Superkar",
    topSpeed: 340,
    accel: 2.85,
    handling: 98,
    braking: 98,
    weight: 1380,
    hp: 720,
    drive: "RWD",
    bodyType: "supercar",
    dimensions: { length: 4.6, width: 1.97, height: 1.2 },
    color: "#e53e3e",
    desc: "3.9L Twin-Turbo V8! Xalqaro dvigatel mukofotlari sovrindori."
  },
  {
    id: "mclaren_720s",
    name: "McLaren 720S Performance",
    category: "hypercar",
    brand: "McLaren",
    price: 315000,
    unlocked: false,
    tier: "Giperkar",
    topSpeed: 345,
    accel: 2.75,
    handling: 98,
    braking: 99,
    weight: 1283,
    hp: 720,
    drive: "RWD",
    bodyType: "hypercar",
    dimensions: { length: 4.54, width: 1.93, height: 1.2 },
    color: "#ed8936",
    desc: "Karbon monokok, kapalak eshiklar va aerokosmik texnologiyalar uyg'unligi."
  },
  {
    id: "bugatti_chiron",
    name: "Bugatti Chiron Pur Sport",
    category: "hypercar",
    brand: "Bugatti",
    price: 3800000,
    unlocked: false,
    tier: "Qirollik Giperkari",
    topSpeed: 420,
    accel: 2.3,
    handling: 97,
    braking: 100,
    weight: 1945,
    hp: 1500,
    drive: "AWD",
    bodyType: "hypercar",
    dimensions: { length: 4.54, width: 2.04, height: 1.21 },
    color: "#3182ce",
    desc: "8.0L W16 Quad-Turbo! 1500 ot kuchi va cheksiz tezlik hukmdori."
  },
  {
    id: "bugatti_bolide",
    name: "Bugatti Bolide Extreme",
    category: "hypercar",
    brand: "Bugatti",
    price: 4500000,
    unlocked: false,
    tier: "Eksklyuziv Trek",
    topSpeed: 480,
    accel: 2.1,
    handling: 99,
    braking: 100,
    weight: 1240,
    hp: 1850,
    drive: "AWD",
    bodyType: "hypercar",
    dimensions: { length: 4.75, width: 2.0, height: 1.0 },
    color: "#1a202c",
    desc: "1850 ot kuchi va bor-yo'g'i 1240 kg vazn! Sayyoramizdagi eng tezkor poyga yirtqichi."
  },
  {
    id: "pagani_huayra",
    name: "Pagani Huayra BC Roadster",
    category: "hypercar",
    brand: "Pagani",
    price: 3500000,
    unlocked: false,
    tier: "San'at Asari",
    topSpeed: 380,
    accel: 2.7,
    handling: 98,
    braking: 99,
    weight: 1250,
    hp: 800,
    drive: "RWD",
    bodyType: "hypercar",
    dimensions: { length: 4.6, width: 2.04, height: 1.17 },
    color: "#4a5568",
    desc: "Carbo-Titanium korpus, Mercedes-AMG V12 Twin-Turbo va 4 ta faol aerodinamik qanotchalar."
  },
  {
    id: "koenigsegg_jesko",
    name: "Koenigsegg Jesko Absolut",
    category: "hypercar",
    brand: "Koenigsegg",
    price: 4200000,
    unlocked: false,
    tier: "Mutlaq Rekordsmen",
    topSpeed: 500, // 500+ km/h
    accel: 2.2,
    handling: 99,
    braking: 100,
    weight: 1390,
    hp: 1600,
    drive: "RWD",
    bodyType: "hypercar",
    dimensions: { length: 4.84, width: 2.03, height: 1.21 },
    color: "#2d3748",
    desc: "Tezlik chegaralarini yo'q qiluvchi shved texnologiyasi! 500 km/h dan yuqori tezlikka mo'ljallangan aerodinamika."
  }
];

// O'yin ichidagi tyuning komponentlari
export const TUNING_PARTS = {
  colors: [
    { name: "Klassik Oq (White Pearl)", hex: "#ffffff", price: 500 },
    { name: "Qora Gentra (Black Onyx)", hex: "#0d0d0d", price: 800 },
    { name: "Afsonaviy Qizil (Ferrari Red)", hex: "#e53e3e", price: 1200 },
    { name: "Okean Moviy (Metallic Blue)", hex: "#1e40af", price: 1000 },
    { name: "Zumrad Yashil (Nardo Green)", hex: "#15803d", price: 1200 },
    { name: "Quyosh Sariq (Gold Yellow)", hex: "#eab308", price: 1100 },
    { name: "Alanga Qizg'ish (Orange Flame)", hex: "#ea580c", price: 1300 },
    { name: "Siyohrang Neon (Cyber Purple)", hex: "#7e22ce", price: 1500 },
    { name: "Hameleon (Chameleon Rainbow)", hex: "#06b6d4", price: 3500, special: "chameleon" }
  ],
  headlightColors: [
    { name: "Ksenon Oq (6000K)", hex: "#ffffff", price: 400 },
    { name: "Lazer Moviy (Ice Blue)", hex: "#38bdf8", price: 800 },
    { name: "Iblis Qizil (Demon Red)", hex: "#ef4444", price: 1200 },
    { name: "Poyga Sariq (GT Amber)", hex: "#fbbf24", price: 600 },
    { name: "Neon Yashil (Toxic Green)", hex: "#4ade80", price: 900 },
    { name: "Binafsha (Cyberpunk Violet)", hex: "#c084fc", price: 1100 }
  ],
  doorStyles: [
    { id: "normal", name: "Standart Ochilish", price: 0 },
    { id: "scissor", name: "Qaychi / Lambo Eshiklar", price: 4500 },
    { id: "gullwing", name: "Kapalak / Qanot Eshiklar", price: 7000 }
  ],
  spoilers: [
    { id: "none", name: "Spoylersiz (Stock)", price: 0 },
    { id: "ducktail", name: "Ducktail (Kichik Sport)", price: 1200 },
    { id: "gt_wing", name: "GT Wing (Poyga Karbon Qanoti)", price: 3500 },
    { id: "massive", name: "Mega Time-Attack Qanot", price: 6500 }
  ],
  rims: [
    { id: "stock", name: "Zavod Diskalari", price: 0 },
    { id: "sport5", name: "5-Spoke Sport Qora", price: 1800 },
    { id: "bbs_mesh", name: "BBS Qavariq To'r (Kumush)", price: 2800 },
    { id: "forged_gold", name: "Forged Racing (Oltin)", price: 4200 },
    { id: "carbon_deep", name: "Ultra Karbon Yengil", price: 6000 }
  ],
  neonUnderglow: [
    { id: "none", name: "Neonsiz", hex: null, price: 0 },
    { id: "neon_blue", name: "Muzdek Moviy Neon", hex: "#00f0ff", price: 1500 },
    { id: "neon_red", name: "Qonli Qizil Neon", hex: "#ff003c", price: 1500 },
    { id: "neon_green", name: "Zaharli Yashil Neon", hex: "#00ff66", price: 1500 },
    { id: "neon_purple", name: "Ultra Binafsha Neon", hex: "#cc00ff", price: 1800 },
    { id: "neon_gold", name: "Boylik Oltini Neon", hex: "#ffd700", price: 2000 }
  ],
  engineStages: [
    { stage: 0, name: "Zavod Dvigateli", hpBonus: 0, topSpeedBonus: 0, accelBonus: 0, price: 0 },
    { stage: 1, name: "Stage 1 (Proshivka & Filtor)", hpBonus: 35, topSpeedBonus: 15, accelBonus: 0.6, price: 2500 },
    { stage: 2, name: "Stage 2 (Pryamotok & Interkuler)", hpBonus: 85, topSpeedBonus: 30, accelBonus: 1.2, price: 6000 },
    { stage: 3, name: "Stage 3 (Twin Turbo & Forged Porshen)", hpBonus: 180, topSpeedBonus: 55, accelBonus: 2.0, price: 15000 },
    { stage: 4, name: "Stage 4 Extreme Race Engine", hpBonus: 320, topSpeedBonus: 85, accelBonus: 2.8, price: 30000 }
  ],
  windowTints: [
    { level: 0, name: "Shaffof Oyna (0%)", price: 0 },
    { level: 0.5, name: "Yengil Qoraytirish (50%)", price: 500 },
    { level: 0.95, name: "Krugovoy Qora Toning (100%)", price: 1200 }
  ]
};
